In [1]:
import mysql.connector
import pandas as pd

In [2]:
connection = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    port="3306",
    password="omkapse@45",
    database="eco_packaging"
)

cursor = connection.cursor()
print("Connected to MySQL successfully!")

Connected to MySQL successfully!

In [3]:
create_table_query = """
CREATE TABLE IF NOT EXISTS materials (
    Material_ID VARCHAR(50),
    Material_Type VARCHAR(100),
    Product_Category VARCHAR(100),
    Strength_MPa DOUBLE,
    Weight_Capacity_kg DOUBLE,
    Biodegradability_Score DOUBLE,
    CO2_Emission_kg DOUBLE,
    Recyclability_Percent DOUBLE,
    Source VARCHAR(100),
    Certification VARCHAR(100),
    Cost_INR DOUBLE,
    Notes VARCHAR(255)
);
"""

cursor.execute(create_table_query)
connection.commit()
print("Table created successfully!")

Table created successfully!

In [4]:
df = pd.read_csv("data.csv")
df.head()

,Material_ID,Material_Type,Product_Category,Strength_MPa,Weight_Capacity_kg,Biodegradability_Score,CO2_Emission_Score_kg,Recyclability_Percentage,Source,Certification,Price_INR,Availability_Status
0,MAT00001,Cellulose,Textiles,22.26,28.23,37.9,11.18,67.7,Supplier A,EcoCert,3720.06,Low Stock
1,MAT00002,Recycled Paper,Electronics,55.91,24.03,68.2,8.64,71.6,Supplier D,FSC,2959.78,Low Stock
2,MAT00003,Recycled Aluminum,Household Items,406.62,1.64,84.5,10.62,34.0,Supplier C,ISO 14001,785.18,In Stock
3,MAT00004,Linen,Textiles,185.90,35.05,41.2,1.13,45.9,Supplier D,ISO 14001,663.17,Pre-Order
4,MAT00005,Recycled Glass,Coatings,443.87,36.80,35.4,1.51,66.1,Supplier A,FSC,3246.13,In Stock

In [6]:
df = df.where(pd.notnull(df), None)

In [7]:
insert_query = """
INSERT INTO materials VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""

for _, row in df.iterrows():
    cursor.execute(insert_query, tuple(row))

connection.commit()
print("Data inserted into MySQL successfully!")

Data inserted into MySQL successfully!

In [8]:
cursor.execute("SELECT COUNT(*) FROM materials")
count = cursor.fetchone()[0]
print("Total records in table:", count)

Total records in table: 20007

In [9]:
query = "SELECT * FROM materials LIMIT 10"
df_sample = pd.read_sql(query, connection)
df_sample

C:\Users\Admin\AppData\Local\Temp\ipykernel_31392\1874502188.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sample = pd.read_sql(query, connection)

,Material_ID,Material_Type,Product_Category,Strength_MPa,Weight_Capacity_kg,Biodegradability_Score,CO2_Emission_kg,Recyclability_Percent,Source,Certification,Cost_INR,Notes
0,MAT00001,Cellulose,Textiles,22.26,28.23,37.9,11.18,67.7,Supplier A,EcoCert,3720.06,Low Stock
1,MAT00002,Recycled Paper,Electronics,55.91,24.03,68.2,8.64,71.6,Supplier D,FSC,2959.78,Low Stock
2,MAT00003,Recycled Aluminum,Household Items,406.62,1.64,84.5,10.62,34.0,Supplier C,ISO 14001,785.18,In Stock
3,MAT00004,Linen,Textiles,185.90,35.05,41.2,1.13,45.9,Supplier D,ISO 14001,663.17,Pre-Order
4,MAT00005,Recycled Glass,Coatings,443.87,36.80,35.4,1.51,66.1,Supplier A,FSC,3246.13,In Stock
5,MAT00006,Linen,Household Items,232.17,83.58,33.0,5.65,67.0,Supplier A,EcoCert,2962.27,Pre-Order
6,MAT00007,Bio-based Polymer,Insulation,367.27,17.18,50.4,14.85,64.0,Supplier C,ISO 14001,2384.59,In Stock
7,MAT00008,Corn Plastic,Food Packaging,404.47,40.72,25.3,13.74,56.7,Supplier B,None,3026.18,Low Stock
8,MAT00009,Linen,Toys,80.01,14.82,79.6,8.32,74.7,Supplier E,Cradle to Cradle,1872.48,Low Stock
9,MAT00010,Hemp Fiber,Construction,259.67,10.00,23.8,2.09,62.7,Supplier D,EcoCert,3321.66,In Stock

In [10]:
query = """
SELECT Material_Type, Biodegradability_Score, Recyclability_Percent, Cost_INR
FROM materials
ORDER BY Biodegradability_Score DESC, Recyclability_Percent DESC
LIMIT 10;
"""
pd.read_sql(query, connection)

C:\Users\Admin\AppData\Local\Temp\ipykernel_31392\4103232448.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, connection)

    Material_Type  Biodegradability_Score  Recyclability_Percent  Cost_INR
0            Jute                   100.0                   92.5   2877.61
1            Jute                   100.0                   92.5   2877.61
2           Linen                   100.0                   46.4   3419.60
3           Linen                   100.0                   46.4   3419.60
4  Certified Wood                   100.0                   19.3   2558.89
5  Certified Wood                   100.0                   19.3   2558.89
6  Natural Rubber                   100.0                   14.9    698.86
7  Natural Rubber                   100.0                   14.9    698.86
8            Jute                   100.0                   11.6    684.75
9            Jute                   100.0                   11.6    684.75

In [11]:
query = """
SELECT Material_Type, Biodegradability_Score, Recyclability_Percent, Cost_INR
FROM materials
WHERE Product_Category = 'Textiles'
ORDER BY Biodegradability_Score DESC;
"""
pd.read_sql(query, connection)

C:\Users\Admin\AppData\Local\Temp\ipykernel_31392\23040466.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, connection)

,Material_Type,Biodegradability_Score,Recyclability_Percent,Cost_INR
0,Certified Wood,99.8,76.8,273.07
1,Bio-based Polymer,99.8,93.8,3865.31
2,Certified Wood,99.8,76.8,273.07
3,Bio-based Polymer,99.8,93.8,3865.31
4,Cork,99.7,68.5,1114.69
...,...,...,...,...
1023,Algae-based Material,20.4,45.2,2150.53
1024,Flax Fiber,20.4,27.2,3290.95
1025,Algae-based Material,20.4,45.2,2150.53
1026,Hemp Fiber,20.3,19.5,2381.27
1027,Hemp Fiber,20.3,19.5,2381.27

In [12]:
query = """
SELECT Material_Type, Cost_INR
FROM materials
ORDER BY Cost_INR ASC
LIMIT 10;
"""
pd.read_sql(query, connection)

C:\Users\Admin\AppData\Local\Temp\ipykernel_31392\183708721.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, connection)

        Material_Type  Cost_INR
0      Organic Cotton    166.00
1      Cork Composite    166.00
2      Organic Cotton    166.00
3      Cork Composite    166.00
4     Seaweed Polymer    166.83
5  Mushroom Composite    166.83
6           Cardboard    166.83
7     Seaweed Polymer    166.83
8  Mushroom Composite    166.83
9           Cardboard    166.83

In [13]:
cursor.close()
connection.close()
print("MySQL connection closed.")

MySQL connection closed.