In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')
df.head()

,Material_ID,Material_Type,Product_Category,Strength_MPa,Weight_Capacity_kg,Biodegradability_Score,CO2_Emission_Score_kg,Recyclability_Percentage,Source,Certification,Price_INR,Availability_Status
0,MAT00001,Cellulose,Textiles,22.26,28.23,37.9,11.18,67.7,Supplier A,EcoCert,3720.06,Low Stock
1,MAT00002,Recycled Paper,Electronics,55.91,24.03,68.2,8.64,71.6,Supplier D,FSC,2959.78,Low Stock
2,MAT00003,Recycled Aluminum,Household Items,406.62,1.64,84.5,10.62,34.0,Supplier C,ISO 14001,785.18,In Stock
3,MAT00004,Linen,Textiles,185.90,35.05,41.2,1.13,45.9,Supplier D,ISO 14001,663.17,Pre-Order
4,MAT00005,Recycled Glass,Coatings,443.87,36.80,35.4,1.51,66.1,Supplier A,FSC,3246.13,In Stock

In [3]:
df.isnull().sum()

Material_ID                    0
Material_Type                  0
Product_Category               0
Strength_MPa                   0
Weight_Capacity_kg             0
Biodegradability_Score         0
CO2_Emission_Score_kg          0
Recyclability_Percentage       0
Source                         0
Certification               1651
Price_INR                      0
Availability_Status            0
dtype: int64

In [4]:
df = df.fillna(df.mean(numeric_only=True))

In [5]:
df = df.fillna("Unknown")

In [9]:
print(df.columns)

Index(['Material_ID', 'Material_Type', 'Product_Category', 'Strength_MPa',
       'Weight_Capacity_kg', 'Biodegradability_Score', 'CO2_Emission_Score_kg',
       'Recyclability_Percentage', 'Source', 'Certification', 'Price_INR',
       'Availability_Status'],
      dtype='object')

In [ ]:
# Normalized numerical features

from sklearn.preprocessing import MinMaxScaler

numeric_cols = [
    "Strength_MPa",
    "Weight_Capacity_kg",
    "Biodegradability_Score",
    "CO2_Emission_Score_kg",
    "Recyclability_Percentage",
    "Price_INR"
]

scaler = MinMaxScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print("Normalized numerical features:")
df[numeric_cols].describe()

Normalized numerical features:

,Strength_MPa,Weight_Capacity_kg,Biodegradability_Score,CO2_Emission_Score_kg,Recyclability_Percentage,Price_INR
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,0.494412,0.501529,0.500018,0.500005,0.500865,0.497604
std,0.288444,0.290326,0.289531,0.287983,0.290621,0.289226
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.243489,0.252071,0.247500,0.249655,0.245000,0.249687
50%,0.490877,0.500303,0.503750,0.502759,0.507000,0.494581
75%,0.742147,0.757022,0.746250,0.748276,0.752000,0.750990
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
# Encoding categorical features

df = pd.get_dummies(
    df,
    columns=[
        "Material_Type",
        "Product_Category",
        "Availability_Status"
    ],
    drop_first=True
)

print("Data after encoding categorical features:")
df.head()

Data after encoding categorical features:

,Material_ID,Strength_MPa,Weight_Capacity_kg,Biodegradability_Score,CO2_Emission_Score_kg,Recyclability_Percentage,Source,Certification,Price_INR,Material_Type_Bio-based Polymer,...,Product_Category_Home Decor,Product_Category_Household Items,Product_Category_Insulation,Product_Category_Kitchen Utensils,Product_Category_Office Supplies,Product_Category_Sports Equipment,Product_Category_Textiles,Product_Category_Toys,Availability_Status_Low Stock,Availability_Status_Pre-Order
0,MAT00001,0.024921,0.275033,0.22375,0.736552,0.677,Supplier A,EcoCert,0.892455,False,...,False,False,False,False,False,False,True,False,True,False
1,MAT00002,0.093601,0.232596,0.60250,0.561379,0.716,Supplier D,FSC,0.701542,False,...,False,False,False,False,False,False,False,False,True,False
2,MAT00003,0.809409,0.006366,0.80625,0.697931,0.340,Supplier C,ISO 14001,0.155481,False,...,False,True,False,False,False,False,False,False,False,False
3,MAT00004,0.358914,0.343943,0.26500,0.043448,0.459,Supplier D,ISO 14001,0.124844,False,...,False,False,False,False,False,False,True,False,False,True
4,MAT00005,0.885437,0.361625,0.19250,0.069655,0.661,Supplier A,FSC,0.773447,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
# CO2 Impact Index

df["CO2_Impact_Index"] = 1 / (df["CO2_Emission_Score_kg"] + 1)

df[["CO2_Emission_Score_kg", "CO2_Impact_Index"]].head()

   CO2_Emission_Score_kg  CO2_Impact_Index
0               0.736552          0.575854
1               0.561379          0.640459
2               0.697931          0.588952
3               0.043448          0.958361
4               0.069655          0.934881

In [14]:
# Cost Efficiency Index

df["Cost_Efficiency_Index"] = df["Recyclability_Percentage"] / (df["Price_INR"] + 1)

df[["Recyclability_Percentage", "Price_INR", "Cost_Efficiency_Index"]].head()

   Recyclability_Percentage  Price_INR  Cost_Efficiency_Index
0                     0.677   0.892455               0.357736
1                     0.716   0.701542               0.420795
2                     0.340   0.155481               0.294250
3                     0.459   0.124844               0.408057
4                     0.661   0.773447               0.372720

In [15]:
# Material Suitability Score

df["Material_Suitability_Score"] = (
    0.4 * df["Strength_MPa"] +
    0.3 * df["Biodegradability_Score"] +
    0.3 * df["Recyclability_Percentage"]
)

df[["Strength_MPa", "Biodegradability_Score",
    "Recyclability_Percentage", "Material_Suitability_Score"]].head()

,Strength_MPa,Biodegradability_Score,Recyclability_Percentage,Material_Suitability_Score
0,0.024921,0.22375,0.677,0.280193
1,0.093601,0.60250,0.716,0.432991
2,0.809409,0.80625,0.340,0.667639
3,0.358914,0.26500,0.459,0.360766
4,0.885437,0.19250,0.661,0.610225

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 59 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Material_ID                          10000 non-null  object
 1   Strength_MPa                         10000 non-null  float64
 2   Weight_Capacity_kg                   10000 non-null  float64
 3   Biodegradability_Score               10000 non-null  float64
 4   CO2_Emission_Score_kg                10000 non-null  float64
 5   Recyclability_Percentage             10000 non-null  float64
 6   Source                               10000 non-null  object
 7   Certification                        10000 non-null  object
 8   Price_INR                            10000 non-null  float64
 9   Material_Type_Bio-based Polymer      10000 non-null  bool
 10  Material_Type_Biodegradable Plastic  10000 non-null  bool
 11  Material_Type_Bioplastic             10000 non-null  bool
 12  Material_Type_Cardboard              10000 non-null  bool
 13  Material_Type_Cellulose              10000 non-null  bool
 14  Material_Type_Certified Wood         10000 non-null  bool
 15  Material_Type_Cork                   10000 non-null  bool
 16  Material_Type_Cork Composite         10000 non-null  bool
 17  Material_Type_Corn Plastic           10000 non-null  bool
 18  Material_Type_Flax Fiber             10000 non-null  bool
 19  Material_Type_Hemp Fiber             10000 non-null  bool
 20  Material_Type_Jute                   10000 non-null  bool
 21  Material_Type_Linen                  10000 non-null  bool
 22  Material_Type_Mushroom Composite     10000 non-null  bool
 23  Material_Type_Mycelium Leather       10000 non-null  bool
 24  Material_Type_Natural Rubber         10000 non-null  bool
 25  Material_Type_Organic Cotton         10000 non-null  bool
 26  Material_Type_Recycled Aluminum      10000 non-null  bool
 27  Material_Type_Recycled Copper        10000 non-null  bool
 28  Material_Type_Recycled Glass         10000 non-null  bool
 29  Material_Type_Recycled Metal         10000 non-null  bool
 30  Material_Type_Recycled PET           10000 non-null  bool
 31  Material_Type_Recycled Paper         10000 non-null  bool
 32  Material_Type_Seaweed Polymer        10000 non-null  bool
 33  Material_Type_Sustainable Bamboo     10000 non-null  bool
 34  Material_Type_Wool                   10000 non-null  bool
 35  Product_Category_Adhesives           10000 non-null  bool
 36  Product_Category_Automotive          10000 non-null  bool
 37  Product_Category_Bags & Luggage      10000 non-null  bool
 38  Product_Category_Coatings            10000 non-null  bool
 39  Product_Category_Construction        10000 non-null  bool
 40  Product_Category_Cosmetics           10000 non-null  bool
 41  Product_Category_Electronics         10000 non-null  bool
 42  Product_Category_Flooring            10000 non-null  bool
 43  Product_Category_Food Packaging      10000 non-null  bool
 44  Product_Category_Footwear            10000 non-null  bool
 45  Product_Category_Furniture           10000 non-null  bool
 46  Product_Category_Home Decor          10000 non-null  bool
 47  Product_Category_Household Items     10000 non-null  bool
 48  Product_Category_Insulation          10000 non-null  bool
 49  Product_Category_Kitchen Utensils    10000 non-null  bool
 50  Product_Category_Office Supplies     10000 non-null  bool
 51  Product_Category_Sports Equipment    10000 non-null  bool
 52  Product_Category_Textiles            10000 non-null  bool
 53  Product_Category_Toys                10000 non-null  bool
 54  Availability_Status_Low Stock        10000 non-null  bool
 55  Availability_Status_Pre-Order        10000 non-null  bool
 56  CO2_Impact_Index                     10000 non-null  float64
 57  Cost_Efficiency_Index                10000 non-null  float64
 58  Material_Suitability_Score           10000 non-null  float64
dtypes: bool(47), float64(9), object(3)
memory usage: 1.4+ MB

In [17]:
df.describe()

,Strength_MPa,Weight_Capacity_kg,Biodegradability_Score,CO2_Emission_Score_kg,Recyclability_Percentage,Price_INR,CO2_Impact_Index,Cost_Efficiency_Index,Material_Suitability_Score
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,0.494412,0.501529,0.500018,0.500005,0.500865,0.497604,0.693042,0.346774,0.498030
std,0.288444,0.290326,0.289531,0.287983,0.290621,0.289226,0.139615,0.215574,0.168994
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.020780
25%,0.243489,0.252071,0.247500,0.249655,0.245000,0.249687,0.571992,0.165145,0.376800
50%,0.490877,0.500303,0.503750,0.502759,0.507000,0.494581,0.665443,0.336245,0.495675
75%,0.742147,0.757022,0.746250,0.748276,0.752000,0.750990,0.800221,0.500265,0.618612
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.988878,0.976035

In [ ]:
df.corr(numeric_only=True)

,Strength_MPa,Weight_Capacity_kg,Biodegradability_Score,CO2_Emission_Score_kg,Recyclability_Percentage,Price_INR,Material_Type_Bio-based Polymer,Material_Type_Biodegradable Plastic,Material_Type_Bioplastic,Material_Type_Cardboard,...,Product_Category_Kitchen Utensils,Product_Category_Office Supplies,Product_Category_Sports Equipment,Product_Category_Textiles,Product_Category_Toys,Availability_Status_Low Stock,Availability_Status_Pre-Order,CO2_Impact_Index,Cost_Efficiency_Index,Material_Suitability_Score
Strength_MPa,1.000000,0.012163,0.001471,-0.003380,-0.001352,-0.000356,0.002984,0.000113,-0.009264,0.007341,...,0.002820,-0.018732,0.001305,-0.014783,-0.003560,0.009450,0.005920,0.003805,-0.006180,0.682791
Weight_Capacity_kg,0.012163,1.000000,-0.006026,-0.000877,-0.011173,-0.002549,0.011046,-0.005128,-0.009853,-0.013136,...,0.016351,-0.018011,-0.007025,0.005087,0.013286,-0.001483,0.026800,0.001809,-0.009181,-0.000558
Biodegradability_Score,0.001471,-0.006026,1.000000,0.000694,0.006516,0.021362,-0.003442,0.014942,0.005980,-0.002076,...,0.014172,-0.011778,0.005318,0.000703,-0.003631,-0.011905,0.007569,-0.000400,0.000493,0.518346
CO2_Emission_Score_kg,-0.003380,-0.000877,0.000694,1.000000,-0.016754,0.002051,0.001274,-0.005934,-0.006281,0.003377,...,-0.016036,-0.005846,0.001022,-0.007387,-0.014000,0.002165,-0.001593,-0.984171,-0.014334,-0.010595
Recyclability_Percentage,-0.001352,-0.011173,0.006516,-0.016754,1.000000,0.021994,0.012253,0.020993,0.003742,0.002809,...,-0.004737,0.001452,0.003841,-0.006457,-0.020071,-0.012723,-0.009419,0.014861,0.928184,0.518339
Price_INR,-0.000356,-0.002549,0.021362,0.002051,0.021994,1.000000,-0.005583,0.008577,-0.013519,-0.006327,...,0.002135,0.007923,-0.003986,0.014857,0.013725,-0.009876,-0.013265,-0.002755,-0.296175,0.022083
Material_Type_Bio-based Polymer,0.002984,0.011046,-0.003442,0.001274,0.012253,-0.005583,1.000000,-0.040797,-0.039802,-0.040523,...,0.010293,0.000752,0.007772,0.027161,-0.014835,0.013303,-0.006149,-0.003319,0.013208,0.006590
Material_Type_Biodegradable Plastic,0.000113,-0.005128,0.014942,-0.005934,0.020993,0.008577,-0.040797,1.000000,-0.039382,-0.040095,...,0.004186,0.001707,0.018140,-0.011512,0.004728,0.004232,0.002216,0.007360,0.021864,0.018587
Material_Type_Bioplastic,-0.009264,-0.009853,0.005980,-0.006281,0.003742,-0.013519,-0.039802,-0.039382,1.000000,-0.039117,...,-0.017939,-0.013137,0.016027,0.014454,-0.000132,-0.008122,0.012403,0.009688,0.006448,-0.001320
Material_Type_Cardboard,0.007341,-0.013136,-0.002076,0.003377,0.002809,-0.006327,-0.040523,-0.040095,-0.039117,1.000000,...,0.009607,-0.016867,-0.009272,-0.015702,-0.001708,-0.012746,0.009599,-0.002403,0.002410,0.005394
Material_Type_Cellulose,0.006689,0.018544,0.012159,0.013606,-0.008888,0.008311,-0.042517,-0.042068,-0.041042,-0.041785,...,-0.001910,0.004877,-0.001979,-0.003494,0.009857,0.004530,0.012992,-0.017318,-0.014544,0.006231
Material_Type_Certified Wood,0.001413,0.015016,0.008602,-0.003991,-0.010905,-0.007728,-0.039240,-0.038826,-0.037879,-0.038565,...,-0.009534,0.010147,0.005420,0.006161,0.005975,0.000105,-0.002957,0.006700,-0.006931,-0.000240
Material_Type_Cork,0.012329,-0.006042,-0.001273,-0.015520,-0.002645,0.004277,-0.039802,-0.039382,-0.038422,-0.039117,...,0.006461,-0.005824,0.008875,0.007250,0.019044,0.005394,-0.002189,0.019069,-0.003975,0.006398
Material_Type_Cork Composite,-0.000794,0.005447,0.008130,0.005373,0.000536,-0.001006,-0.038843,-0.038433,-0.037495,-0.038174,...,0.008714,0.003630,-0.020462,-0.010093,-0.015151,0.008531,-0.012922,-0.005083,0.001333,0.003913
Material_Type_Corn Plastic,-0.003179,-0.003827,-0.008845,-0.001317,0.009249,-0.001343,-0.038384,-0.037979,-0.037053,-0.037724,...,0.009812,0.007194,0.000063,0.010683,-0.014298,0.015199,-0.006472,0.000282,0.010064,-0.001945
Material_Type_Flax Fiber,-0.004894,0.012480,-0.009533,0.004630,-0.008887,-0.000068,-0.040025,-0.039602,-0.038637,-0.039336,...,-0.001336,0.022826,-0.013009,-0.000445,0.008916,0.017333,-0.000324,-0.005509,-0.010862,-0.012827
Material_Type_Hemp Fiber,0.003187,0.005677,-0.014968,0.018888,-0.020353,0.001450,-0.040247,-0.039822,-0.038851,-0.039554,...,0.005437,-0.009136,-0.008716,0.006200,0.001265,0.003508,0.002633,-0.019542,-0.021746,-0.016017
Material_Type_Jute,-0.009245,0.006421,-0.004349,0.022171,0.002842,0.004908,-0.040192,-0.039767,-0.038797,-0.039500,...,0.015236,-0.001780,-0.003879,-0.007949,0.010890,-0.003933,-0.004778,-0.022549,-0.000808,-0.007081
Material_Type_Linen,-0.004987,-0.007568,0.004253,-0.016771,-0.001174,0.009643,-0.039802,-0.039382,-0.038422,-0.039117,...,-0.013059,0.020991,-0.003044,-0.004757,-0.002529,0.005394,0.001179,0.017218,-0.003065,-0.001824
Material_Type_Mushroom Composite,0.002424,0.012794,-0.007149,0.011725,-0.003381,-0.005202,-0.039858,-0.039437,-0.038475,-0.039172,...,0.008769,-0.008372,-0.003164,-0.007272,0.006927,0.014015,0.000801,-0.014039,0.001736,-0.003764
Material_Type_Mycelium Leather,-0.001185,-0.002713,-0.005507,0.016503,0.011938,-0.002357,-0.038384,-0.037979,-0.037053,-0.037724,...,0.012335,-0.000369,-0.009799,-0.011669,0.000576,0.007044,0.000493,-0.016977,0.009009,0.002519
Material_Type_Natural Rubber,0.008642,-0.007420,-0.010988,0.007258,0.004982,0.001981,-0.039691,-0.039271,-0.038314,-0.039007,...,-0.017743,-0.027592,0.001977,-0.002115,-0.009498,0.008413,-0.007067,-0.006618,0.003492,0.002823
Material_Type_Organic Cotton,0.002881,0.012177,-0.000626,-0.001132,-0.002120,-0.010985,-0.038957,-0.038545,-0.037605,-0.038286,...,-0.011470,0.005860,0.001227,0.006831,-0.008026,-0.003742,-0.004494,-0.000047,0.003424,0.000551
Material_Type_Recycled Aluminum,-0.001314,-0.000229,-0.000026,-0.004845,0.009171,0.014857,-0.040906,-0.040474,-0.039487,-0.040202,...,-0.022230,0.006220,0.006232,0.002325,0.004476,0.007889,-0.008372,0.004070,0.003184,0.003821
Material_Type_Recycled Copper,-0.003689,-0.021258,-0.005795,-0.008516,-0.012172,0.002949,-0.040025,-0.039602,-0.038637,-0.039336,...,0.010801,0.010700,-0.010638,-0.012390,-0.017315,-0.023008,0.015309,0.007753,-0.008044,-0.011776
Material_Type_Recycled Glass,0.013212,0.001256,0.014048,0.011521,-0.000143,-0.000545,-0.038729,-0.038320,-0.037385,-0.038062,...,-0.011036,0.003889,0.011524,0.007374,0.007188,-0.016100,0.008537,-0.005324,-0.000101,0.016167
Material_Type_Recycled Metal,0.003546,-0.004425,-0.013249,-0.008990,0.003599,0.009364,-0.039297,-0.038882,-0.037934,-0.038620,...,-0.002236,-0.007256,-0.009186,-0.008552,-0.011137,-0.003691,0.004617,0.005241,-0.001368,-0.002533
Material_Type_Recycled PET,-0.006939,-0.000994,-0.014368,-0.018799,0.013788,0.003321,-0.040523,-0.040095,-0.039117,-0.039825,...,-0.011992,0.011904,0.004796,-0.006254,-0.027641,-0.014962,-0.018000,0.020412,0.011633,-0.005009
Material_Type_Recycled Paper,-0.011972,-0.010485,0.008953,0.017105,-0.019826,-0.003293,-0.037629,-0.037231,-0.036324,-0.036981,...,-0.003772,0.003851,0.014324,0.010040,0.012380,-0.005530,0.009200,-0.017760,-0.014599,-0.013800
Material_Type_Seaweed Polymer,0.006455,-0.016438,0.012972,-0.013370,0.000969,-0.010464,-0.040136,-0.039712,-0.038744,-0.039445,...,0.000848,-0.011338,-0.013222,0.001695,-0.000866,-0.010275,0.001158,0.011429,0.007478,0.011574
Material_Type_Sustainable Bamboo,-0.008298,0.000985,0.005412,-0.020130,0.000743,-0.008581,-0.040247,-0.039822,-0.038851,-0.039554,...,0.017512,-0.009136,0.000722,-0.005684,0.001265,-0.007641,0.010409,0.020099,0.000731,-0.002500
Material_Type_Wool,0.003491,-0.002390,0.006917,-0.009897,0.004301,-0.001497,-0.039127,-0.038714,-0.037770,-0.038454,...,0.017956,-0.001963,0.008109,0.016187,0.003806,0.006583,-0.017026,0.009192,0.000805,0.008158
Product_Category_Adhesives,0.003949,-0.009681,0.001578,0.002996,0.011777,0.004286,0.005570,-0.000584,0.006461,-0.011992,...,-0.052189,-0.052244,-0.053558,-0.053123,-0.053232,-0.003750,0.004723,-0.004200,0.010970,0.009583
Product_Category_Automotive,0.003297,-0.003623,0.001868,0.001223,-0.000200,0.002185,-0.021682,0.022596,-0.006925,-0.003463,...,-0.051353,-0.051407,-0.052700,-0.052272,-0.052380,-0.015774,0.010758,-0.001889,-0.000395,0.003108
Product_Category_Bags & Luggage,0.020972,0.008847,0.004265,-0.001448,0.024038,-0.008352,0.016217,0.000439,-0.004797,0.005881,...,-0.051577,-0.051631,-0.052930,-0.052500,-0.052608,0.018612,0.001504,0.002053,0.023484,0.028912
Product_Category_Coatings,-0.003634,0.008820,-0.001176,-0.007956,0.003904,-0.009191,-0.001995,-0.014943,0.008301,0.001903,...,-0.053883,-0.053940,-0.055297,-0.054847,-0.054960,-0.009581,-0.002413,0.006061,0.007132,-0.001072
Product_Category_Construction,-0.001083,0.001543,-0.006293,-0.005534,0.005687,-0.016076,-0.000180,0.000775,-0.018736,0.006132,...,-0.052795,-0.052851,-0.054180,-0.053740,-0.053850,0.006336,-0.003713,0.006777,0.012797,-0.001040
Product_Category_Cosmetics,0.022086,0.002165,-0.010317,0.015247,-0.007165,0.004793,-0.010879,-0.007654,0.001673,0.012110,...,-0.052133,-0.052188,-0.053501,-0.053067,-0.053175,-0.013232,0.009939,-0.014911,-0.008542,0.006080
Product_Category_Electronics,-0.001221,0.004945,-0.002683,0.001007,-0.005443,-0.012104,0.003762,0.002258,0.004418,0.000376,...,-0.050506,-0.050560,-0.051831,-0.051410,-0.051516,-0.007989,-0.002121,-0.000323,0.002781,-0.005021
Product_Category_Flooring,0.015654,-0.005068,-0.015609,-0.003067,0.001942,-0.000663,-0.000960,-0.014421,0.019314,-0.001851,...,-0.051856,-0.051911,-0.053216,-0.052784,-0.052892,0.006060,0.028316,0.004786,0.000551,0.003666
Product_Category_Food Packaging,-0.001967,-0.007734,-0.005026,0.002236,0.006333,-0.010509,-0.005663,-0.004726,0.004463,0.018862,...,-0.054741,-0.054799,-0.056177,-0.055721,-0.055835,-0.012529,0.008503,-0.001256,0.012256,-0.000659
Product_Category_Footwear,-0.004680,-0.000879,0.015622,-0.012342,-0.000934,-0.006568,-0.011679,-0.001140,0.013406,0.001882,...,-0.051072,-0.051126,-0.052412,-0.051986,-0.052093,0.014757,-0.011404,0.011671,0.001139,0.004352
Product_Category_Furniture,-0.014204,0.004052,-0.016073,0.017945,-0.015224,0.009464,-0.000088,0.007955,-0.018664,0.008606,...,-0.052740,-0.052796,-0.054124,-0.053684,-0.053794,-0.005948,-0.000493,-0.016184,-0.016084,-0.025813
Product_Category_Home Decor,0.004202,-0.010115,-0.009100,-0.003893,-0.014879,-0.002948,0.008666,-0.011431,-0.007076,-0.006169,...,-0.053068,-0.053125,-0.054461,-0.054018,-0.054129,0.000855,-0.008190,0.005414,-0.016700,-0.009485
Product_Category_Household Items,-0.004878,0.005809,0.001375,0.018843,0.000777,0.005227,-0.003607,0.014044,-0.007931,0.002691,...,-0.052022,-0.052077,-0.053387,-0.052954,-0.053062,-0.001805,-0.010917,-0.018838,-0.003772,-0.002223
Product_Category_Insulation,-0.002492,-0.007278,0.016977,0.009635,-0.006855,0.011494,-0.008771,0.006374,0.003833,0.004615,...,-0.052299,-0.052355,-0.053672,-0.053236,-0.053345,0.000499,0.013801,-0.010780,-0.008606,0.003487
Product_Category_Kitchen Utensils,0.002820,0.016351,0.014172,-0.016036,-0.004737,0.002135,0.010293,0.004186,-0.017939,0.009607,...,1.000000,-0.052244,-0.053558,-0.053123,-0.053232,0.021712,-0.015769,0.016582,-0.008977,0.006766
Product_Category_Office Supplies,-0.018732,-0.018011,-0.011778,-0.005846,0.001452,0.007923,0.000752,0.001707,-0.013137,-0.016867,...,-0.052244,1.000000,-0.053615,-0.053179,-0.053288,-0.006026,0.009266,0.004156,-0.001845,-0.018093
Product_Category_Sports Equipment,0.001305,-0.007025,0.005318,0.001022,0.003841,-0.003986,0.007772,0.018140,0.016027,-0.009272,...,-0.053558,-0.053615,1.000000,-0.054517,-0.054629,0.009485,-0.005277,-0.004163,0.004183,0.005606
Product_Category_Textiles,-0.014783,0.005087,0.000703,-0.007387,-0.006457,0.014857,0.027161,-0.011512,0.014454,-0.015702,...,-0.053123,-0.053179,-0.054517,1.000000,-0.054185,-0.003319,-0.007544,0.007190,-0.009857,-0.013063
Product_Category_Toys,-0.003560,0.013286,-0.003631,-0.014000,-0.020071,0.013725,-0.014835,0.004728,-0.000132,-0.001708,...,-0.053232,-0.053288,-0.054629,-0.054185,1.000000,0.006634,-0.007214,0.015861,-0.024288,-0.014651
Availability_Status_Low Stock,0.009450,-0.001483,-0.011905,0.002165,-0.012723,-0.009876,0.013303,0.004232,-0.008122,-0.012746,...,0.021712,-0.006026,0.009485,-0.003319,0.006634,1.000000,-0.498455,0.000291,-0.011759,-0.006231
Availability_Status_Pre-Order,0.005920,0.026800,0.007569,-0.001593,-0.009419,-0.013265,-0.006149,0.002216,0.012403,0.009599,...,-0.015769,0.009266,-0.005277,-0.007544,-0.007214,-0.498455,1.000000,-0.000138,-0.001088,0.003073
CO2_Impact_Index,0.003805,0.001809,-0.000400,-0.984171,0.014861,-0.002755,-0.003319,0.007360,0.009688,-0.002403,...,0.016582,0.004156,-0.004163,0.007190,0.015861,0.000291,-0.000138,1.000000,0.012245,0.010059
Cost_Efficiency_Index,-0.006180,-0.009181,0.000493,-0.014334,0.928184,-0.296175,0.013208,0.021864,0.006448,0.002410,...,-0.008977,-0.001845,0.004183,-0.009857,-0.024288,-0.011759,-0.001088,0.012245,1.000000,0.474897
Material_Suitability_Score,0.682791,-0.000558,0.518346,-0.010595,0.518339,0.022083,0.006590,0.018587,-0.001320,0.005394,...,0.006766,-0.018093,0.005606,-0.013063,-0.014651,-0.006231,0.003073,0.010059,0.474897,1.000000

In [ ]:
df.to_csv("../cleaned_materials.csv", index=False)